platform :ios, '7.0' #プラットフォームの指定 iOS6.0以上
xcodeproj './wa-shoi.xcodeproj'
pod 'Parse-iOS-SDK'
pod 'EAIntroView', '~> 2.6.0'
pod 'AFNetworking', '~> 2.0'
pod 'Realm'
pod 'LINEActivity'
pod 'YLGIFImage'
pod 'SWTableViewCell'
pod 'Facebook-iOS-SDK'
pod 'ParseFacebookUtils'
